Update no selinux option.yml

diff --git a/.github/workflows/no selinux option.yml b/.github/workflows/no selinux option.yml
--- a/.github/workflows/no selinux option.yml
+++ b/.github/workflows/no selinux option.yml
@@ -1,4 +1,4 @@
-name: Build ScamsungKernel NonSelinux
+name: Build SolsticeRay NonSelinux
 
 on:
   push:
@@ -40,9 +40,9 @@ jobs:
         BRANCH="${{ github.event.inputs.kernel_branch }}"
         
         if [ -z "$BRANCH" ]; then
-          git clone --depth=1 --recursive "$REPO" $GITHUB_WORKSPACE/kernel_src
+          git clone --depth=1 --recursive "$REPO" $GITHUB_WORKSPACE/blxyzz
         else
-          git clone --depth=1 -b "$BRANCH" --recursive "$REPO" $GITHUB_WORKSPACE/kernel_src
+          git clone --depth=1 -b "$BRANCH" --recursive "$REPO" $GITHUB_WORKSPACE/blxyzz
         fi
 
         mkdir -p $GITHUB_WORKSPACE/toolchains && cd $GITHUB_WORKSPACE/toolchains
@@ -63,7 +63,7 @@ jobs:
         export ARCH=arm64 SUBARCH=arm64 OUT_DIR=$GITHUB_WORKSPACE/out USE_CCACHE=1 CCACHE_DIR=~/.cache/ccache
         export GCC_64=aarch64-linux-android- GCC_32=arm-linux-androideabi-
         
-        ccache -M 5G && mkdir -p $OUT_DIR && cd $GITHUB_WORKSPACE/kernel_src
+        ccache -M 5G && mkdir -p $OUT_DIR && cd $GITHUB_WORKSPACE/blxyzz
         DEFCONFIG="${{ github.event.inputs.defconfig_name || 'vendor/a23_eur_open_defconfig' }}"
 
         make -j$(nproc --all) O=$OUT_DIR ARCH=arm64 CROSS_COMPILE=$GCC_64 CROSS_COMPILE_ARM32=$GCC_32 CC=clang CLANG_TRIPLE=aarch64-linux-gnu- $DEFCONFIG
@@ -73,11 +73,11 @@ jobs:
       run: |
         rm -rf $GITHUB_WORKSPACE/zip_stage && mkdir -p $GITHUB_WORKSPACE/zip_stage
         
-        if [ -d "$GITHUB_WORKSPACE/ScamsungKernel" ]; then
-          cp -r $GITHUB_WORKSPACE/ScamsungKernel/* $GITHUB_WORKSPACE/zip_stage/
+        if [ -d "$GITHUB_WORKSPACE/AnyKernel3-A235F" ]; then
+          cp -r $GITHUB_WORKSPACE/AnyKernel3-A235F/* $GITHUB_WORKSPACE/zip_stage/
           find $GITHUB_WORKSPACE/zip_stage/ -name "*.zip" -type f -delete
         else
-          echo "ERROR: ScamsungKernel folder not found!" && exit 1
+          echo "ERROR: AnyKernel3-A235F folder not found!" && exit 1
         fi
         
         if [ -f "$GITHUB_WORKSPACE/out/arch/arm64/boot/Image" ]; then
@@ -88,9 +88,9 @@ jobs:
         
         [ -f "$GITHUB_WORKSPACE/out/arch/arm64/boot/dtbo.img" ] && cp $GITHUB_WORKSPACE/out/arch/arm64/boot/dtbo.img $GITHUB_WORKSPACE/zip_stage/dtbo.img
         
-        cd $GITHUB_WORKSPACE/zip_stage && zip -r9 $GITHUB_WORKSPACE/ScamsungKernel.zip ./*
+        cd $GITHUB_WORKSPACE/zip_stage && zip -r9 $GITHUB_WORKSPACE/AnyKernel3-A235F.zip ./*
         
-        cd $GITHUB_WORKSPACE/kernel_src
+        cd $GITHUB_WORKSPACE/blxyzz
         KERNEL_VERSION=$(make kernelversion)
 
         echo "RELEASE_TAG=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
@@ -99,9 +99,9 @@ jobs:
     - name: Upload to GitHub Release
       uses: softprops/action-gh-release@v2
       with:
-        files: ScamsungKernel.zip
+        files: AnyKernel3-A235F.zip
         tag_name: "${{ env.RELEASE_TAG }}"
-        name: "Scamsung Kernel v${{ env.LINUX_VERSION }}"
+        name: "SolsticeRay Kernel v${{ env.LINUX_VERSION }}"
         body: |
           ### Kernel Build Details
           - **Linux Version**: `v${{ env.LINUX_VERSION }}`
